language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo echo "deb http://ftp.de.debian.org/debian experimental main" >> /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install qt5-default
script:
  - qmake
  - make
